import type { Metadata } from "next";
import localFont from "next/font/local";
import { ContextComp } from "./context/context";
import ReactQueryProvider from "./reactqueryProvider";
import Footer from "./footer";
import "./globals.css";
import Navbar from "./navbar";
import Modal from "../../components/modal";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider >
        <ContextComp>
          <section>
            <Modal/>
            <Navbar />
            {children}
            <Footer />
          </section>
        </ContextComp>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
